### ISSUE TITLE
Using bracket notation in template strings

### ISSUE THREAD

**Issue by amohoste** [RMLio/yarrrml-parser#1]
I was wondering if it's possible to use the bracket-notation (as defined in [jsonpath](https://github.com/json-path/JsonPath)) in template strings. When I try to generate an RML file with the mapping defined below I currently get the error `Couldn't generate the RML mapping file, check the source.`. When I remove the brackets I don't get an error.

```
prefixes:
  gbfs: "http://example.com/terms#"
  ex: "http://example.com/"
  geo: "http://www.w3.org/2003/01/geo/wgs84_pos#"

sources:
  station:
    access: data.json
    referenceFormulation: jsonpath
    iterator: $[*]
  
mappings:
  # System
  system_info:
    sources: station
    s: ex:stations/$(fields.number)
    po:
      - [geo:lat, $(fields.position"["0"]"), xsd:double]
```

I have tried the following notations but they all generate the same error:
```
$(fields.position"["0"]")
$(fields.position"[0]")
$(fields.position[0])
```
Data: 
[data.json.zip](https://github.com/RMLio/yarrrml-parser/files/2269638/data.json.zip)
