### ISSUE TITLE
Problem with results of function "decide"

### ISSUE THREAD

**Issue by ritamargherita** [RMLio/yarrrml-parser#111]
### Description
I am using the function "idlab-fn:decide". The function works properly, but the result is not exactly what expected. 

### Steps

xml example:

<?xml version="1.0" encoding="UTF-8"?>
<resource
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://datacite.org/schema/kernel-4
http://schema.datacite.org/meta/kernel-4.1/metadata.xsd">
<identifier identifierType="DOI">10.17026/dans-zk5-883b</identifier>
<rightsList>
<rights>info:eu-repo/semantics/restrictedAccess</rights>
<rights
rightsURI="https://dans.knaw.nl/en/about/organisation-and-policy/legal-information/DANSLicence.pdf">DANS
License</rights>
</rightsList>
</resource>

YARRRML example:

prefixes:
  doi: http://doi.org/
  opl: http://www.w3id.org/odissei/ns/terms_of_use_representation/
  idlab-fn: http://example.com/idlab/function/

mappings:
  test:
    sources:
      - ['example.xml~xpath', 'resource']
    s: doi:$(identifier)
    po:
       - predicates: opl:hasAccess
          objects: 
              - function: idlab-fn:decide
                parameters:
                  - [idlab-fn:str, "$(rightsList/rights[1])"]
                  - [idlab-fn:expectedStr, "info:eu-repo/semantics/restrictedAccess"]
                  - [idlab-fn:result, opl:Restricted]

results RDF:

<http://doi.org/10.17026%2Fdans-zk5-883b> opl:hasAccess "http://www.w3id.org/odissei/ns/terms_of_use_representation/Restricted".

Ideally we would want:
<http://doi.org/10.17026%2Fdans-zk5-883b> opl:hasAccess opl:Restricted. 

When producing RDF, YARRRML replace the opl: in the function with the actual prefix, and it considers it as a string

### Environment
OS

**Comment by bjdmeest** [comment]
Hi @ritamargherita,

Matey expands the prefix because the Termtype of an objectMap is Literal by default.
If you add `type: iri` in the object description, I receive the results you want :)

```yaml
prefixes:
  doi: http://doi.org/
  opl: http://www.w3id.org/odissei/ns/terms_of_use_representation/
  idlab-fn: http://example.com/idlab/function/

mappings:
  test:
    sources:
       - ['example.xml~xpath', 'resource']
    s: doi:$(identifier)
    po:
      - predicates: opl:hasAccess
        objects:
          - function: idlab-fn:decide
            parameters:
              - [idlab-fn:str, "$(rightsList/rights[1])"]
              - [idlab-fn:expectedStr, "info:eu-repo/semantics/restrictedAccess"]
              - [idlab-fn:result, opl:Restricted]
            type: iri
```

(the last line is important ;) )

Let me know if this solves your problem, if so, feel free to close this issue! :)
