### ISSUE TITLE
datatype is not taken into account when a function is used

### ISSUE THREAD

**Issue by bjdmeest** [RMLio/yarrrml-parser#12]
Following 2 yarrrml snippets don't result in a correct addition of the datatype
```
      - p: ex:numberOfApplications
        o:
          - function: grel:trim
            parameters:
              - [grel:valueParameter, $(Number of applications)]
            datatype: xsd:int
```
```
      - p: ex:numberOfApplications
        o:
          - value:
            - function: grel:trim
              parameters:
                - [grel:valueParameter, $(Number of applications)]
            datatype: xsd:int
```

In the first, the datatype is ignored, in the second, the result of the objectmap is not a functiontermmap, but a `"[object Object]"` string
