### ISSUE TITLE
Mapping with one target using shortcuts not mapped

### ISSUE THREAD

**Issue by valentinoli** [RMLio/yarrrml-parser#126]
### Description
The target is not mapped when we have a mapping with one target using shortcuts 

### Steps
YARRRML:
```yml
mapping:
  person:
    subjects:
      - value: "http://example.org/{id}"
        targets: ["data/dump.ttl.gz~void", "turtle", "gzip"]
```

Output:
```turtle
<prefixes skipped for brevity>

mex:rules_000 a <http://rdfs.org/ns/void#Dataset>.
mex:person a rr:TriplesMap;
    rdfs:label "person".
mex:s_000 a rr:SubjectMap.
mex:person rr:subjectMap mex:s_000.
mex:s_000 rr:constant "http://example.org/{id}".
```

However, the following works:

```yml
mapping:
  person:
    subjects:
      - value: "http://example.org/{id}"
        targets:
          - ["data/dump.ttl.gz~void", "turtle", "gzip"]
```

```turtle
<prefixes skipped for brevity>

mex:rules_000 a void:Dataset.
mex:target_000 a rmlt:LogicalTarget;
    rdfs:label "data/dump.ttl.gz-void-turtle-gzip";
    rmlt:serialization formats:Turtle;
    rmlt:compression comp:gzip;
    rmlt:target mex:void_000.
mex:void_000 a void:Dataset;
    void:dataDump <file://data/dump.ttl.gz>.
mex:person a rr:TriplesMap;
    rdfs:label "person".
mex:s_000 a rr:SubjectMap.
mex:person rr:subjectMap mex:s_000.
mex:s_000 rr:constant "http://example.org/{id}";
    rml:logicalTarget mex:target_000.

```

### Environment
yarrrml-parser v1.3.0 (JS library)
