### ISSUE TITLE
XPath Syntax in Templates

### ISSUE THREAD

**Issue by robert-mieth** [RMLio/yarrrml-parser#133]
### Issue type: :question: Question
I've been trying to use XPath axes such as `parent::*` or `ancestor::*` within templates in nested mappings. I assumed that I could use them like a rr:parentTriplesMap in the RMLMapper.

XML:
```
<?xml version='1.0' encoding='UTF-8'?>
<ex:root xmlns:ex="http://example.com/">
    <ex:organization>
        <ex:id>1</ex:id>
            <ex:department>
                <ex:team>
                    <ex:member>
                        <ex:name>John Doe</ex:name>
                    </ex:member>
                </ex:team>
            </ex:department>
    </ex:organization>
</ex:root>
```

YARRRML:
```
prefixes:
 ex: http://example.com/

mappings:
 organization:
    sources:
      - [xpath_example.xml~xpath, "root//organization"]
    subjects: ex:organization/$(id)
    po:
      - [a, ex:organization]
      - p: ex:hasMember
        o:
          - mapping: member
            condition:
              function: equal
              parameters:
                - [str1, $(id), s]
              # use of xpath axis
              # - [str2, $(ancestor::organization/id), o]
                - [str2, $(//organization/id), o]
 member:
  sources:
   - [xpath_example.xml~xpath, "root//member"]
  subjects: ex:member/$(name)
  po:
      - [a, ex:member]
```

I personally quite like the option to deal with (more heavily) nested XML by using XPath axes.

Is there a way to use XPath axes with the YARRRML Parser?
