### ISSUE TITLE
Variable information for predicate not transformed properly

### ISSUE THREAD

**Issue by bsteenwi** [RMLio/yarrrml-parser#14]
Executing the following script:

```
prefixes:
  ex: "http://example.com/"
mappings:
  nodes:
    sources:
      - [track_metadata.xml~xpath, /osm/node]
    s: "ex:node/$(@id)"
    po:
      - ["ex:test$(@id)", "$(tag/@v)"]
```

with XML data

```
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6">
 <node id="245756888" visible="true" version="6" changeset="58029209" timestamp="2018-04-12T09:43:16Z" user="Russ McD" uid="346601" lat="27.2047267" lon="77.5087183">
  <tag k="source" v="AND"/>
 </node>
</osm>
```
results in `<http://example.com/node/245756888> <http://example.com/test$(@id)> "AND".`
So it looks like the predicate information is not escaped correctly.
