### ISSUE TITLE
Interpret function output as an iri

### ISSUE THREAD

**Issue by florent-andre** [RMLio/yarrrml-parser#140]
Hy there,
Thanks for the good parser here and documentation ! 

Seeing this `rdf:Property~iri`.
I would like to interpret a function output as a well formed `iri` string (ex: `hrdf:IdentifierType`).
I don't catch the good syntax.

Here is my example function and "commented tries" : 
```yaml
          - function: rb:replace
            parameters:
              - parameter: rb:scriptName
                value: replace
              - parameter: rb:scriptParameters
                value: -s '$(@type)' -p 'hropen:' -r 'hrdf:'
            # type: iri
            # datatype: iri
```
