### ISSUE TITLE
condition on map doesn't get picked up when subject has a function

### ISSUE THREAD

**Issue by bjdmeest** [RMLio/yarrrml-parser#144]
### Description
condition on map doesn't get picked up when subject has a function

### Steps
Following YARRRML doesn't take the condition into account

```yaml
prefixes:
  grel: http://users.ugent.be/~bjdmeest/function/grel.ttl#
  idlab-fn: http://example.com/idlab/function/

mappings:
  person:
    sources:
     - [source_1.csv~csv]
    s:
      function: grel:array_join
      parameters:
        - [grel:p_array_a, "http://example.org/"]
        - [grel:p_array_a, "$(three)"]
    condition:
      function: idlab-fn:notEqual
      parameters:
        - [grel:valueParameter, "$(three)"]
        - [grel:valueParameter2, ""]
    po:
      - [a, schema:Person]
```
