### ISSUE TITLE
grel:toLowerCase applied to iri removes url encoding from string

### ISSUE THREAD

**Issue by henrieglesorotos** [RMLio/yarrrml-parser#151]
### Description
-  Entity IRIs must be url encoded to be valid
- When applying grel:toLowerCase to iris using the shortcut syntax, the URL encoding is stripped from the value the function is applied to. 

### Steps
- take input:

`country_label: "United Kingdom"`

- Apply following yarrrrml mapping to source field with mapping from input:

``` 
          s:
             function: grel:toLowerCase
             parameters:
                - [ grel:valueParameter, prefix:country_$(country_label) ]
           po:
             - [ a, prefix:Country ]
 ```

- error returned:
`The subject "http://www.prefix.com/country_united kingdom" is not a valid IRI. Skipped`

However, if I write the mapping without shortcuts the output is as expected. See below. Full mapping without shortcuts:

```
    s:
      function: grel:toLowerCase
      parameters:
        - parameter: grel:valueParameter
          value: prefix:country_$(country_label)
    po:
      - [ a, prefix_country ]
```

- expected output:
`<http://www.prefix.com/country_united%20kingdom>`

### Environment
- Java 11 
- MacOS Big Sur, 11.4
