### ISSUE TITLE
Equal function ignores mapping in parameters

### ISSUE THREAD

**Issue by pheyvaer** [RMLio/yarrrml-parser#155]
### Description
Equal function ignores mapping in parameters.

```yaml
- p: ex:test
  o: 
    mapping: projects
    condition:
      function: equal 
      parameters: 
        - [str1, $(id), o]
        - [str2, $(employee-id), s]
```

In `[str1, $(id), o]` the third element `o` is ignored. It's always `s`.
In `[str2, $(employee-id), s]` the third element `s` is ignored. It's always `o`.

### Steps
The two following snippets return the same RML. while the child and parent of the join condition should be switched.

```yaml
- p: ex:test
  o: 
    mapping: projects
    condition:
      function: equal 
      parameters: 
        - [str1, $(id), o]
        - [str2, $(employee-id), s]
```

```yaml
- p: ex:test
  o: 
    mapping: projects
    condition:
      function: equal 
      parameters: 
        - [str1, $(id), s]
        - [str2, $(employee-id), o]
```

### Environment
v1.3.3 of the parser.
