### ISSUE TITLE
Cannot use XML namespaces in XPath for subject generation

### ISSUE THREAD

**Issue by rorlic** [RMLio/yarrrml-parser#159]
### Description
Using a XML namespace in a subject definition will trim anything after and including the colon (:).

### Steps
Consider the following YARRRML input: 
```yaml
prefixes:
  ex: http://earthquake.usgs.gov/
  dc: http://purl.org/dc/terms/

mappings:
  earthquake:
    sources:
      - [earthquake.xml~xpath, /ns:feed/ns:entry]
    s: ex:earthquake/$(./ns:id)#id
    po:
      - [a, ex:earthquake]
      - [dc:title, $(./ns:title)]
```

When generating the RML, there is an error in the RML for the subject.

Expected behavior: `map:s_000 rdf:type rr:SubjectMap ; rr:template "http://earthquake.usgs.gov/earthquake/{./ns:id}#id" .`
Actual behavior: `map:s_000 rdf:type rr:SubjectMap ; rr:template "http://earthquake.usgs.gov/earthquake/{./ns" .`

**Note** that the source iterator (`map:source_000 rml:iterator "/ns:feed/ns:entry" ;`) and `dc:title` (`map:om_001 rml:reference "./ns:title" ;`) are produced correctly.

**Note** that in the RMLStreamer there is one [example](https://github.com/RMLio/RMLStreamer/tree/8c19776f6707a40b74d5ee2f9870533a274ed728/src/test/resources/exampleLanguageMap) with a default XML namespace, but it has been commented out.

### Environment
Using online [Matey](https://rml.io/yarrrml/matey/#).
