### ISSUE TITLE
How to represent one-to-many and nested relationships

### ISSUE THREAD

**Issue by qzc438** [RMLio/yarrrml-parser#179]
### Issue type: :question: Question

As shown in the excel [query-result.csv](https://github.com/RMLio/yarrrml-parser/files/9857656/query-result.csv), I am asking how to represent one-to-many and nested relationships:

1. AHU1A has two sub-equipment VAV2-3 and VAV2-4.
2. VAV2-4 has one sensor VAV2-4.DPR and this sensor have a sub-sensor VAV2-4.DPRPOS.

**Comment by bjdmeest** [comment]
See the example YARRRML below, does this answer your question?

```yaml
prefixes:
  ex: "http://example.com/"
  idlab-fn: "http://example.com/idlab/function/"
  grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"

mappings:
  Equipment:
    sources:
      - ['data.csv~csv']
    s: http://example.com/equiment/$(Equipment)
    po:
      - [a, ex:Equipment]
      - [ex:subEquipment, http://example.com/equiment/$(Sub-Equipment)~iri]
      - [ex:hasSensor, http://example.com/sensor/$(Sensor)~iri]
  Sensor:
    sources:
      - ['data.csv~csv']
    s: http://example.com/sensor/$(Sensor)
    po:
      - [a, ex:Sensor]
      - [ex:subSensor, http://example.com/sensor/$(Sub-Sensor)~iri]

```
