### ISSUE TITLE
Predicate cannot be set from data

### ISSUE THREAD

**Issue by Melchyore** [RMLio/yarrrml-parser#186]
### Description
Hi, i want to reference a predicate from the data, but it causes the following error: `Cannot read properties of undefined (reading '@id')`. I think the predicate needs to be explicitly set but there isn't a way to reference it from the data?

### Steps

Yarrrml (not working version)

```yaml
prefixes:
    odrl: http://www.w3.org/ns/odrl/2/
    xsd: http://www.w3.org/2001/XMLSchema#
    rdfs: http://www.w3.org/2000/01/rdf-schema#
    rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#

mappings:
  policy:
    sources:
      - [input~csv]
    s: $(uid)
    po:
      - [a, $(type)~iri]
      - [$(rule), ex:test~iri]
```

Yarrrml (working version)

```yaml
prefixes:
    odrl: http://www.w3.org/ns/odrl/2/
    xsd: http://www.w3.org/2001/XMLSchema#
    rdfs: http://www.w3.org/2000/01/rdf-schema#
    rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#

mappings:
  policy:
    sources:
      - [input~csv]
    s: $(uid)
    po:
      - [a, $(type)~iri]
      - [odrl:permission, ex:test~iri]
```

Data

```csv
type,uid,rule
http://www.w3.org/ns/odrl/2/Agreement,https://example.com/agreement_01,http://www.w3.org/ns/odrl/2/permission
```

### Environment
Windows 10
Latest version of this package

Thank you!
