### ISSUE TITLE
Generating object URI without entity

### ISSUE THREAD

**Issue by namedgraph** [RMLio/yarrrml-parser#187]
### Description
I'm using a mapping like this:
```yml
mappings:
  CarMaker:
    sources: Something
    s: makers:$(carMakerId)
    po:
      - [ a, skos:Concept ]
  Car:
    sources: Something
    s: cars:$(carId)
    po:
      - p: cars:madeBy
        o:
          - mapping: CarMaker
```

I would like to avoid the `CarMaker` entity (and any triples it produces) however, and simply create `cars:$(carId) cars:madeBy makers:$(carMakerId)` triples for `Car`.
I tried removing `po` from `CarMaker` but that is not allowed.

Is that doable already?

### Why it is useful

Not all object resources need to be entities which have their own properties, some can simply be standalone URI values.

### Existing features it breaks

Unknown

**Comment by namedgraph** [comment]
That's what I tried using RMLMapper 6.1.3 and it came out as a URI but in quotes, i.e. as a string literal. Maybe that's a bug rather than a feature request :)

**Comment by bjdmeest** [comment]
Haha, no, sorry, that's bug from me!
The YARRRML should be below (it makes literals by default), the `~iri` specifies it to be a named node

```yaml
mappings:
  Car:
    sources: Something
    s: cars:$(carId)
    po:
      - p: cars:madeBy
        o: makers:$(carMakerId)~iri
```

**Comment by joma3** [comment]
Does not work for me: 

```
mappings:
  Car:
    sources: Something
    subject: ex:$(./@id)
    predicateobjects:
      - predicates: rdf:type
        objects: 
                 - values: ex:$(./@name)  
```
