### ISSUE TITLE
Cross-product of links between instances

### ISSUE THREAD

**Issue by namedgraph** [RMLio/yarrrml-parser#192]
### Issue type: :bug: Bug

```yaml
sources:
  Smth:
    access: input.ndjson
    referenceFormulation: jsonpath
    iterator: "$.key[*]"
mappings:
  Concept:
    sources: Smth
    graph: smth:$(@)
    s: smth:$(@)#this
    po:
      - [ a, skos:Concept ]
      - [ skos:prefLabel, $(@) ]
  Document:
    sources: Smth
    graph: smth:$(@)
    s: smth:$(@)
    po:
      - [ a, foaf:Document ]
      - p: foaf:primaryTopic
        o:
          - mapping: Concept
```

I am getting a cross-product in the output, i.e. if there are N rows, I'm getting this `Document` output:
```turtle
<instance1> foaf:primaryTopic <instance1#this> .
<instance1> foaf:primaryTopic <instance2#this> .
...
<instance1> foaf:primaryTopic <instanceN#this> .
<instance2> foaf:primaryTopic <instance1#this> .
<instance2> foaf:primaryTopic <instance2#this> .
...
<instance2> foaf:primaryTopic <instanceN#this> .
...
<instanceN> foaf:primaryTopic <instance1#this> .
<instanceN> foaf:primaryTopic <instance2#this> .
...
<instanceN> foaf:primaryTopic <instanceN#this> .
```

Where I only want to simply "pair" respective `Document` and `Concept` instances:
```turtle
<instance1> foaf:primaryTopic <instance1#this> .
<instance2> foaf:primaryTopic <instance2#this> .
...
<instanceN> foaf:primaryTopic <instanceN#this> .
```
Is there a way to express what I need with YARRRML?

**Comment by pheyvaer** [comment]
Hi @namedgraph, how does your input data look like?

**Comment by namedgraph** [comment]
One row looks like this:
```json
{"key":["aaaaaa","bbbbbbbb","cccc","ddddddd"]}
```

I added `sources` to the mapping BTW.

**Comment by pheyvaer** [comment]
It's only possible if there is a unique way to identify a row and the only link the rows that are the same. For example, if the every row has a index you can add a `condition` to your `mapping` so that it only links when the indexes of the rows as equal.

**Comment by namedgraph** [comment]
I see... I might need to add that.

These are annoying shortcomings IMO. It would not be a problem using XSLT, for example.

**Comment by namedgraph** [comment]
But wait... I would need a different `iterator` then?

**Comment by pheyvaer** [comment]
No, that is not needed.

**Comment by namedgraph** [comment]
But in the mapping I'm using array item (e.g. `cccc`) as the value: `$(@)`
It's those values I need to compare, not row IDs. If I was to add IDs for those values, I would need to change the whole JSON structure within the array?

**Comment by pheyvaer** [comment]
No, that's not needed. The following works for me
```yaml
sources:
  Smth:
    access: data.json
    referenceFormulation: jsonpath
    iterator: "$.key[*]"
mappings:
  Concept:
    sources: Smth
    s: ex:$(@)#this
    po:
      - [ a, skos:Concept ]
      - [ skos:prefLabel, $(@) ]
  Document:
    sources: Smth
    s: ex:$(@)
    po:
      - [ a, foaf:Document ]
      - p: foaf:primaryTopic
        o:
          - mapping: Concept
            condition:
              function: equal
              parameters:
                - [str1, $(@)]
                - [str2, $(@)]
```
