### ISSUE TITLE
Cannot create named blank node as subject

### ISSUE THREAD

**Issue by bjdmeest** [RMLio/yarrrml-parser#198]
### Description
I wanna build something like https://rml.io/test-cases/#rmltc0001b-csv , but YARRRML below doesn't contain the termtype

### Steps
```yaml
mappings:
  loc:
    s:
      value: $(ID)_$(loc)
      type: blank
```

becomes (snippet)

```turtle
map:s_000 rml:reference "firstname" ;
	rdf:type rr:SubjectMap .
```

### Environment
Matey, and latest yarrrml-parser (1.5.2)
