### ISSUE TITLE
Cannot reference a mapping from within itself with blank node as subject

### ISSUE THREAD

**Issue by Melchyore** [RMLio/yarrrml-parser#200]
### Description
I want to create an ordered list using `rdf:first` and `rdf:rest` from an array (the number of array elements is random). It works in Matey but doesn't work with the latest YARRRML parser.

### Steps
```yaml
permission_constraints_xone:
    sources:
      - permission_constraint_xone
    s: null
    po:
      - [rdf:first, this:policies/$(policy_id)/permissions/$(rule_id)/logical_constraints/xone/$(id)~iri]
      - p: rdf:rest # If `next`= null, then: rdf:rest rdf:nil.
        o:
          - value: rdf:nil
            type: iri
            condition:
              function: idlab-fn:isNull
              parameters:
                - [idlab-fn:str, $(next)]
      - p: rdf:rest # If `next` != null, then: rdf:rest _:x (where x is a random number)
        o:
          - mapping: permission_constraints_xone
            # condition:
            #   function: equal
            #   parameters:
            #     - [str1, $(next)]
            #     - [str2, $(id)]
```

The above snippet show produces the following RDF (which is wrong: the blank nodes for the objects are wrong, for the first triple, it should be `rdf:rest _:1`):

```ttl
_:0 rdf:first <https://example.com/policies/1035993210/permissions/2049408449/logical_constraints/xone/1658331773>;
  rdf:rest _:0 .

_:1 rdf:first <https://example.com/policies/1035993210/permissions/2049408449/logical_constraints/xone/3045330922>;
  rdf:rest _:1, rdf:nil .
```

But with Matey, it produces a correct RDF:

```ttl
_:b34_0 rdf:first <https://example.com/policies/1035993210/permissions/2049408449/logical_constraints/xone/1658331773> ;
	rdf:rest _:b34_1 . # Here, this is a correct reference to the next triple.

_:b34_1 rdf:first <https://example.com/policies/1035993210/permissions/2049408449/logical_constraints/xone/3045330922> ;
	rdf:rest rdf:nil.
```

Please do note that the condition has been commented because using it in local doesn't work, the object is not created, whereas in Matey, it works (and it has been uncommented in Matey for this example).

### Environment
Matey and latest yarrrml-parser 1.5.4
