### ISSUE TITLE
graph function object results in `mapping.graphs.forEach is not a function`

### ISSUE THREAD

**Issue by bjdmeest** [RMLio/yarrrml-parser#206]
### Description
graph function object results in `mapping.graphs.forEach is not a function`

### Steps
see

```yaml
    graph:
      function: grel:array_join
      parameters:
        - [ grel:p_array_a, "bridgestone-qualifications:" ]
        - parameter: grel:p_array_a
          value:
            function: grel:string_md5
            parameters:
              - [ grel:valueParameter, $(label) ]
```

### Environment
/
