### ISSUE TITLE
Union operator not picked up by parser

### ISSUE THREAD

**Issue by jpwijbenga** [RMLio/yarrrml-parser#207]
I'm not sure in the docs I can find the restrictions on the JSON path allowed in the subjects expression. Is union supported? Like this example?

```json
{
  "timestamp": "2024-03-05T13:05:47.812Z",
  "updates": [
    {
      "after": {
        "id": 123
      },
      "before": {
        "id": 456
      }
    },
    {
      "after": {
        "id": 123
      },
      "before": {
        "id": 456
      }
    },
    {
      "after": {
        "id": 123
      },
      "before": {
        "id": 456
      }
    }
  ]
}
```

``` yaml
prefixes:
 ex: "http://example.com/"

mappings:
  person:
    sources:
      - ['data.json~jsonpath', '$.updates[*].before,after']
    s: http://example.com/$(id)
    po:
      - [a, foaf:Person]
```

### Description
Is the docs missing restrictions on json path allowed or am I doing something wrong?

### Steps
See example code. Tested json path with online tool at jsonpath.com

### Environment
Online Matey / yarrrml parser v1.6.1
