### ISSUE TITLE
Condition on single object is ignored

### ISSUE THREAD

**Issue by pheyvaer** [RMLio/yarrrml-parser#21]
A condition on a single object is ignored, i.e., the corresponding RML rules for the condition are not generated.

An example YARRRML document is
```
prefixes:
  ex: http://example.org/

mappings:
  test:
    sources:
      - [data/papers.csv~csv]
    s: ex:$(id)
    po:
      - p: a
        o:
          - value: ex:MyClass
            type: iri
            condition:
              function: fn:equal
              parameters:
                - [ex:value1, $(type)]
                - [ex:value2, woop]

```
