### ISSUE TITLE
Condition on mapping with blank node as subject gives error

### ISSUE THREAD

**Issue by pheyvaer** [RMLio/yarrrml-parser#31]
Input:

```
  read:
    sources:
      - [goodreads_library_export.csv~csv]
    condition:
        function: idlab-fn:notEqual
        parameters:
         - [grel:valueParameter, $(Date Read)]
         - [grel:valueParameter2, ""]
    po:
      - [a, schema:ReadAction]
```
Error:
```
TypeError: Cannot read property 'length' of undefined
    at expandSubjects (/Users/pieter/.nvm/versions/node/v12.13.0/lib/node_modules/@rmlio/yarrrml-parser/lib/expander.js:84:42)
    at expandMappings (/Users/pieter/.nvm/versions/node/v12.13.0/lib/node_modules/@rmlio/yarrrml-parser/lib/expander.js:47:9)
    at expand (/Users/pieter/.nvm/versions/node/v12.13.0/lib/node_modules/@rmlio/yarrrml-parser/lib/expander.js:32:3)
    at RMLGenerator.convert (/Users/pieter/.nvm/versions/node/v12.13.0/lib/node_modules/@rmlio/yarrrml-parser/lib/abstract-generator.js:40:28)
    at Object.<anonymous> (/Users/pieter/.nvm/versions/node/v12.13.0/lib/node_modules/@rmlio/yarrrml-parser/bin/parser.js:56:23)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'INVALID_YARRRML'
}
```
