### ISSUE TITLE
Overwrite references

### ISSUE THREAD

**Issue by pheyvaer** [RMLio/yarrrml-parser#35]
Allow users to overwrite references used in the rules. For example, if you have the following

```
mappings:
  person:
    po:
      - [schema:name, $(name)]
```
then you could (either via the library or CLI) say that `name` is always "John".
This means that `name` is no longer taken from the data source. Actually, the rules are then (internally) rewritten to
```
mappings:
  person:
    po:
      - [schema:name, John]
```

@bjdmeest What do you think?

**Comment by bjdmeest** [comment]
I like the idea of constants, but I'd make it very clear in the mapping that it's a constant, eg prefixing it with `_C.`. And only allow single-level constants (for now).

eg
```yaml
constants:
  name: John
  city: Schellebelle
mappings:
  director:
    source: ""Let's pretend there's a good source formulation here"
    s: https://ex.com/people/${_C.name}
    po:
      p: ex:livesIn
      o: ${_C.city}
```

**Comment by pheyvaer** [comment]
Yes indeed. I forgot to add that. I would not for them to use something like `_C` though, but I would add something like

```
external: 
  - name
```
that you explicitly say that it has to be provided via for example the CLI.

**Comment by bjdmeest** [comment]
But what if you have a reference `name` and a constant `name`? you can't use both?

**Comment by pheyvaer** [comment]
What do you mean? Can you give an example?

**Comment by bjdmeest** [comment]
If you have a csv with a `name` column, and an external `name` defined,
then depending on which mapping you're in (more specifically, using which source),
the `name` reference will either be overwritten or not

```yaml
mappings:
  director:
    source: "CSV with a name column"
    s: https://ex.com/people/${name} # what to pick here? external or reference?
  houses:
    source: "CSV without name column"
    s: https://ex.com/houses/${name} # external value?
```

That sounds confusion to me
