### ISSUE TITLE
Join condition with two references in child/parent is incorrectly parsed

### ISSUE THREAD

**Issue by pheyvaer** [RMLio/yarrrml-parser#44]
```
      - p: schema:creator
        o:
          mapping: project
          condition:
            function: equal
            parameters:
              - [str1, $(id)_$(name)]
              - [str2, $(id)_$(name)]
```
results in 
```
:jc_0 rr:child "id)_$(name";
    rr:parent "id)_$(name".
```
