### ISSUE TITLE
equal shortcut does not work everywhere

### ISSUE THREAD

**Issue by bjdmeest** [RMLio/yarrrml-parser#51]
### Description
the [Referring to other mappings](https://rml.io/yarrrml/spec/#referring-to-other-mappings) shortcut doesn't work in all cases

### Steps
following mapping fails to generate the right RML doc:

```yaml
mappings:
  mapping:
    sources:
      - ['data.csv~csv']
    s: ex:$(id)
    po:
      - p: ex:p
        o: ex:o
        condition:
          function: equal
          parameters:
            - [str1, $(type)]
            - [str2, "1"]
```

The shortcut isn't recognized in this case.
