### ISSUE TITLE
Function with empty parameter list works, but without parameters doesn't get parsed properly

### ISSUE THREAD

**Issue by bjdmeest** [RMLio/yarrrml-parser#53]
### Description
Function with empty parameter list works, but without parameters doesn't get parsed properly

### Steps
Try the following without the line with the comment

```yaml
prefixes:
  ex: "http://example.com/"
  grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"
  idlab-fn: "http://example.com/idlab/function/"

mappings:
  person:
    sources:
      - ['student.csv~csv']
    s:
      function: grel:array_join
      parameters:
        - [grel:p_array_a, "http://example.com/person/"]
        - parameter: grel:p_array_a
          value:
            function: idlab-fn:random
            parameters: [] # This is needed atm, bug in the YARRRML parser
    po:
      - [a, ex:Person]
```

### Environment
Node 12, Windows
