### ISSUE TITLE
Accessing array elements in YARRRML

### ISSUE THREAD

**Issue by DylanVanAssche** [RMLio/yarrrml-parser#54]
I try to access the latitude and the longitude of the `location` property as separately properties.
This JSONPath is valid: `$.[*].location.value.coordinates.[0]` following jsonpath.com, however YARRRML doesn't accept this path in Matey.

**data.json**
```
[{
        "location": {
            "type": "geo:json",
            "value": {
                "type": "Point",
                "coordinates": [
                    4.410527945,
                    51.211220384
                ]
            }
        }
    }]
```

**YARRRML rules**
```
prefixes:
  ex: "http://example.com#"
  geo: "http://www.w3.org/2003/01/geo/wgs84_pos#"

mappings:
  location:
    sources:
      - ['data.json~jsonpath', '$.[*]']
    s: http://example.com/$(location.value.coordinates)
    po:
      - [a, geo:SpatialThing]
      - [geo:lon, $(location.value.coordinates[0])]
      - [geo:lat, $(location.value.coordinates[1])]
```

**Comment by pheyvaer** [comment]
The problem is that this YARRRML is not valid YAML because of the use of square brackets in the JSON paths. The following YARRRML works

```
prefixes:
  ex: "http://example.com#"
  geo: "http://www.w3.org/2003/01/geo/wgs84_pos#"

mappings:
  location:
    sources:
      - ['data.json~jsonpath', '$.[*]']
    s: http://example.com/$(location.value.coordinates)
    po:
      - [a, geo:SpatialThing]
      - [geo:lon, "$(location.value.coordinates[0])"]
      - [geo:lat, "$(location.value.coordinates[1])"]
```
