### ISSUE TITLE
create blank node as object

### ISSUE THREAD

**Issue by bjdmeest** [RMLio/yarrrml-parser#59]
### Description
I'd expect the following to work (see last lines)
```yaml
prefixes:
  ex: "http://example.com/"

mappings:
  person:
    sources:
      - ['data.json~jsonpath', '$.persons[*]']
    s: http://example.com/$(firstname)
    po:
      - [a, foaf:Person]
      - [ex:name, $(firstname)]
      - p: ex:nationality                                                                             
        o:
          type: blank
```

Instead I need to do smth like

```yaml
      - p: ex:nationality                                                                             
        o: _:other~iri
```

Which doesn't feel right
### Why it is useful
You might want to create blank node objects
### Existing features it breaks
None
