### ISSUE TITLE
Function parameter is translated as rr:constant

### ISSUE THREAD

**Issue by DylanVanAssche** [RMLio/yarrrml-parser#64]
### Description
A function parameter like `str1` is translated to RML rules as an `rr:constant: <str1>` instead of applying `str1` as a parameter for a function

### Steps

1. Create these nested functions
2. `str` stuff what is used in the examples for `equal` is now used a `rr:constant`

**YARRRML rules**
```
prefixes:
  ex: "http://example.coml#"
  grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"
  idlab-fn: "http://example.com/idlab/function/"

mappings:
  apple:
    sources:
      - ["apple.csv~csv"]
    s: http://example.com#J_$(ID)
    po:
      - p: ex:other_fruit
        o:
          - mapping: bananas
            condition:
              function: grel:boolean_and
              parameters:
                - parameter: grel:param_rep_b
                  value:
                    function: idlab-fn:equal
                    parameters:
                      - [str1, "$(ID)"]
                      - [str2, "$(ID)"]
                - parameter: grel:param_rep_b
                  value:
                    function: idlab-fn:equal
                    parameters:
                      - [str1, "$(Taste)"]
                      - [str2, "$(Taste)"]
  
  bananas:
    sources:
      - ["bananas.csv~csv"]
    s: http://example.com#$(ID)
    po:
      - [a, ex:Banana]
```

**RML rules**
```
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix map: <http://mapping.example.com/>.

map:fn_0 rr:predicateObjectMap map:pomexec_0, map:pom_2, map:pom_5.
map:fn_1 rr:predicateObjectMap map:pomexec_1, map:pom_3, map:pom_4.
map:fn_2 rr:predicateObjectMap map:pomexec_2, map:pom_6, map:pom_7.
map:jc_0 a <http://semweb.mmlab.be/ns/fnml#FunctionTermMap>;
    <http://semweb.mmlab.be/ns/fnml#functionValue> map:fn_0.
map:map_apple_0 rml:logicalSource map:source_0;
    a rr:TriplesMap;
    rdfs:label "apple";
    rr:subjectMap map:s_0;
    rr:predicateObjectMap map:pom_0.
map:map_bananas_0 rml:logicalSource map:source_1;
    a rr:TriplesMap;
    rdfs:label "bananas";
    rr:subjectMap map:s_1;
    rr:predicateObjectMap map:pom_1.
map:om_0 a rr:ObjectMap;
    rr:parentTriplesMap map:map_bananas_0;
    rml:joinCondition map:jc_0.
map:om_1 a rr:ObjectMap;
    rr:constant "ex:Banana";
    rr:termType rr:IRI.
map:om_2 a rr:ObjectMap, <http://semweb.mmlab.be/ns/fnml#FunctionTermMap>;
    <http://semweb.mmlab.be/ns/fnml#functionValue> map:fn_1.
map:om_3 a rr:ObjectMap;
    rml:reference "ID";
    rr:termType rr:Literal.
map:om_4 a rr:ObjectMap;
    rml:reference "ID";
    rr:termType rr:Literal.
map:om_5 a rr:ObjectMap, <http://semweb.mmlab.be/ns/fnml#FunctionTermMap>;
    <http://semweb.mmlab.be/ns/fnml#functionValue> map:fn_2.
map:om_6 a rr:ObjectMap;
    rml:reference "Taste";
    rr:termType rr:Literal.
map:om_7 a rr:ObjectMap;
    rml:reference "Taste";
    rr:termType rr:Literal.
map:omexec_0 rr:constant "http://users.ugent.be/~bjdmeest/function/grel.ttl#boolean_and";
    rr:termType rr:IRI.
map:omexec_1 rr:constant "http://example.com/idlab/function/equal";
    rr:termType rr:IRI.
map:omexec_2 rr:constant "http://example.com/idlab/function/equal";
    rr:termType rr:IRI.
map:pm_0 a rr:PredicateMap;
    rr:constant <ex:other_fruit>.
map:pm_1 a rr:PredicateMap;
    rr:constant rdf:type.
map:pm_2 a rr:PredicateMap;
    rr:constant <http://users.ugent.be/~bjdmeest/function/grel.ttl#param_rep_b>.
map:pm_3 a rr:PredicateMap;
    rr:constant <str1>.
map:pm_4 a rr:PredicateMap;
    rr:constant <str2>.
map:pm_5 a rr:PredicateMap;
    rr:constant <http://users.ugent.be/~bjdmeest/function/grel.ttl#param_rep_b>.
map:pm_6 a rr:PredicateMap;
    rr:constant <str1>.
map:pm_7 a rr:PredicateMap;
    rr:constant <str2>.
map:pmexec_0 rr:constant <https://w3id.org/function/ontology#executes>.
map:pmexec_1 rr:constant <https://w3id.org/function/ontology#executes>.
map:pmexec_2 rr:constant <https://w3id.org/function/ontology#executes>.
map:pom_0 a rr:PredicateObjectMap;
    rr:predicateMap map:pm_0;
    rr:objectMap map:om_0.
map:pom_1 a rr:PredicateObjectMap;
    rr:predicateMap map:pm_1;
    rr:objectMap map:om_1.
map:pom_2 a rr:PredicateObjectMap;
    rr:predicateMap map:pm_2;
    rr:objectMap map:om_2.
map:pom_3 a rr:PredicateObjectMap;
    rr:predicateMap map:pm_3;
    rr:objectMap map:om_3.
map:pom_4 a rr:PredicateObjectMap;
    rr:predicateMap map:pm_4;
    rr:objectMap map:om_4.
map:pom_5 a rr:PredicateObjectMap;
    rr:predicateMap map:pm_5;
    rr:objectMap map:om_5.
map:pom_6 a rr:PredicateObjectMap;
    rr:predicateMap map:pm_6;
    rr:objectMap map:om_6.
map:pom_7 a rr:PredicateObjectMap;
    rr:predicateMap map:pm_7;
    rr:objectMap map:om_7.
map:pomexec_0 rr:predicateMap map:pmexec_0;
    rr:objectMap map:omexec_0.
map:pomexec_1 rr:predicateMap map:pmexec_1;
    rr:objectMap map:omexec_1.
map:pomexec_2 rr:predicateMap map:pmexec_2;
    rr:objectMap map:omexec_2.
map:s_0 a rr:SubjectMap;
    rr:template "http://example.com#J_{ID}".
map:s_1 a rr:SubjectMap;
    rr:template "http://example.com#{ID}".
map:source_0 a rml:LogicalSource;
    rml:source "apple.csv";
    rml:referenceFormulation ql:CSV.
map:source_1 a rml:LogicalSource;
    rml:source "bananas.csv";
    rml:referenceFormulation ql:CSV.

```

### Environment

**Java**
```
$ java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment Zulu12.3+11-CA (build 12.0.2+3)
OpenJDK 64-Bit Server VM Zulu12.3+11-CA (build 12.0.2+3, mixed mode, sharing)
```

**OS**
```
Ubuntu 18.04 LTS x64 Linux
```
