### ISSUE TITLE
Please add documentation of YARRRML syntax for nested objects and array mapping

### ISSUE THREAD

**Issue by Simo-climb** [RMLio/yarrrml-parser#67]
Hi @pheyvaer

I found [this issue](https://github.com/RMLio/RML-Mapper/issues/37) in looking for an example of using RML and YARRRML to map nested objects and arrays. This was one of the few examples around that I could find with nested objects.

How do you generate the blank node objectMap triple from YARRRML that maps to the nested Acitivty array in the example issue ?

I couldn't track down any specific mention of how to deal with nested levels of these in the relevant specs.

Does YARRRML support deeply nested structures ? Any documentation links ?

I've tried to reconstruct the above person RML model using the matey YARRRML editor and RML generator but without an example I'm not getting far.

As another suggestion you could extend your twitter yarrrml example to map the user mentions array to some triple values. e.g. screen name

```

[
  {
    "created_at":"Thu Nov 22 01:50:31 +0000 2018",
    "id":1065422239141638144,
    "id_str":"1065422239141638144",
    "text":"@pejacoby Hi there, Paul. Sorry to hear you're having trouble. You can also manually enter the code(s) by pressing\u2026 https:\/\/t.co\/ydFxDWbMpf",
    "truncated":true,
    "entities":{
      "hashtags":[

      ],
      "symbols":[

      ],
      "user_mentions":[
        {
          "screen_name":"pejacoby",
          "name":"Paul Jacoby",
          "id":36056095,
          "id_str":"36056095",
          "indices":[
            0,
            9
          ]
        }
      ],
```

A more trivial example would be the following with the aim of mapping the Street value to ex:StreetName "Smth"
```
{
    "persons": [
        {
            "firstname": "John",
            "lastname": "Doe",
        
        "Address": [
            { "Street": "Smith",
            "Suburb": "Bland"
                
            }
            ]
                },
        {
            "firstname": "Jane",
            "lastname": "Smith"
        },
        {
            "firstname": "Sarah",
            "lastname": "Bladinck"
        }
    ]
}

```
The closest I got to a mapping was only to the Address array with all values returned as the literal value using the following
```
prefixes:
  ex: http://example.com/

base: http://example.com/base#

sources:
  file:
    access: data.json
    referenceFormulation: jsonpath
    iterator: "$.persons[*]"
    
  
mappings:
  tweet:
    sources: file
    s: ex:$(firstname)
    po:
      - [a, foaf:Person]
      - [ex:name, $(firstname)]
      - p: ex:Address
        o:
        - [$(Address)]
```

Many thanks in advance

Simon

**Comment by pheyvaer** [comment]
Hi @Simo-climb 

It would be possible to generate RDF from such a data source if it has ids for both the people and the addresses. In that case the YARRRML rules would something like this

```
prefixes:
  ex: http://example.org/

sources:
  data1:
    access: data.json
    referenceFormulation: jsonpath
    iterator: "$.persons[*]"
  data2:
    access: data.json
    referenceFormulation: jsonpath
    iterator: "$.persons[*].Address.[*]"
  
mappings:
  person:
    sources: data1
    s: ex:$(firstname)
    po:
      - [a, foaf:Person]
      - [ex:name, $(firstname)]
      - p: ex:Address
        o:
          - mapping: address
            condition:
              function: equal
              parameters:
                - [str1, $(personID)] # ID of person under `persons`
                - [str2, $(person)] # ID of person under `Address`

  address:
    sources: data2
    s: ex:$(Street)_$(Suburb)
    po: 
      - [ex:Street, $(Street)]
      - [ex:Suburb, $(Suburb)]
```

**Comment by Simo-climb** [comment]
Thanks @pheyvaer 

so if I understand correctly, the method of iterating through each nested object or array is by a mapping to each and every node level.

Then is the only way to map objects and predicates via the condition matching ? 

Can the fact that a node is nested under a parent be used to assert that there is a relation that exists if the ID doesn't exist - perhaps a constructed URI ?  

To clarify my understanding I assume the mapping between sources and the condition are a java based operation rather than a triple store aka SPARQL operation. 

If it relies on a ID condition, can you please point me to the list of functions and conditions. The spec only shows equals, isValid and isSet.

Many thanks

Simon

**Comment by pheyvaer** [comment]
> so if I understand correctly, the method of iterating through each nested object or array is by a mapping to each and every node level.

Yes.

> Then is the only way to map objects and predicates via the condition matching ?

Yes indeed.

> Can the fact that a node is nested under a parent be used to assert that there is a relation that exists if the ID doesn't exist - perhaps a constructed URI ?

No, the main reason is a limitation of JSONPath: you are not able to refer to the parent of an object.

> To clarify my understanding I assume the mapping between sources and the condition are a java based operation rather than a triple store aka SPARQL operation.

In the case of the RMLMapper yes. It looks at the actual data to see where the links are.

> If it relies on a ID condition, can you please point me to the list of functions and conditions. The spec only shows equals, isValid and isSet.

At list of the default functions in the RMLMapper can be found [here](https://rml.io/docs/rmlmapper/default-functions/). But it's also possible to include your own custom functions.

**Comment by Simo-climb** [comment]
Thanks @pheyvaer 
Very helpful mate. Thanks for your time in replying.  I note that all your answers were documented, but it was just a little difficult finding them between all the various sources, e.g. specs, yarrrml tutorial and website.  The tool is looking good so I'm sure you'll have much more great work to come. Thanks again

**Comment by pdehaye** [comment]
Would you consider using [JSONPath Plus](https://github.com/JSONPath-Plus/JSONPath), which includes the option of grabbing the parent with `^`, or the property names with `~`?

**Comment by pheyvaer** [comment]
Hi @pdehaye 

Thanks for the suggestion. Could you open an issue [here](https://github.com/RMLio/rmlmapper-java) regarding this, as it is more relevant there? Thanks

**Comment by godlinn** [comment]
Is there a possibility to create a mapping between an object and multiple nested objects? E.g., if person has multiple addresses and addresses is a nested object like this:

`
[
    {
        "person_id": 1,
        "addresses": [
            {
                "id": 1,
                "street": Frivjrn Str.,
                ...
            },
            {
                "id": 2,
                "street": Vejrnrijv Str.,
                ...
            },
        ]
    },
    ...
]
`
I understand how to implement the case for 1 to 1 mapping, where each person has exactly 1 address, but I don't understand how to create a 1 to n address if a person have multiple addresses and I could not find any documentation for this case.

I would be very grateful for help.

**Comment by pheyvaer** [comment]
Hi @godlinn, could you make a separate issue for that together with the minimal data and YARRRML rules you already have? Thanks!

**Comment by namedgraph** [comment]
@pheyvaer how would this work with a mapping like this?
```yaml
mappings:
  Concept:
    sources: Smth
    graph: smth:$(@)
    s: smth:$(@)#this
    po:
      - [ a, skos:Concept ]
      - [ skos:prefLabel, $(@) ]
  Document:
    sources: Smth
    graph: smth:$(@)
    s: smth:$(@)
    po:
      - [ a, foaf:Document ]
      - p: foaf:primaryTopic
        o:
          - mapping: Concept
```

I am getting a cross-product in the output, i.e. if there are N rows, I'm getting this `Document` output:
```turtle
<instance1> foaf:primaryTopic <instance1#this> .
<instance1> foaf:primaryTopic <instance2#this> .
...
<instance1> foaf:primaryTopic <instanceN#this> .
<instance2> foaf:primaryTopic <instance1#this> .
<instance2> foaf:primaryTopic <instance2#this> .
...
<instance2> foaf:primaryTopic <instanceN#this> .
...
<instanceN> foaf:primaryTopic <instance1#this> .
<instanceN> foaf:primaryTopic <instance2#this> .
...
<instanceN> foaf:primaryTopic <instanceN#this> .
```
Where I only want to "pair" respective`Document` and `Concept` instances:
```turtle
<instance1> foaf:primaryTopic <instance1#this> .
<instance2> foaf:primaryTopic <instance2#this> .
...
<instanceN> foaf:primaryTopic <instanceN#this> .
```

Is there a solution to this?
