### ISSUE TITLE
Nested functions in condition don't use referencingObjectMaps

### ISSUE THREAD

**Issue by bjdmeest** [RMLio/yarrrml-parser#68]
### Description
The following YARRRML code doesn't use referencingObjectMaps in the nested functions

```yaml
prefixes:
  ex: http://example.com#
  grel: http://users.ugent.be/~bjdmeest/function/grel.ttl#
  idlab-fn: "http://example.com/idlab/function/"

mappings:
  myMapping:
    sources:
      - ["data.csv~csv"]
    s: ex:$(ID)
    po:
      - [a, ex:Person]
      - [ex:label, $(name)]
      - p: ex:isFriendsWith
        o:
          - mapping: myOtherMapping
            condition:
              function: grel:boolean_and
              parameters:
                - parameter: grel:param_rep_b
                  value:
                    function: idlab-fn:equal
                    parameters:
                      - [grel:valueParameter, "$(otherID)", s]
                      - [grel:valueParameter2, "$(friendID)", o]
                - parameter: grel:param_rep_b
                  value:
                    mapping: myOtherMapping
                    function: idlab-fn:equal
                    parameters:
                      - [grel:valueParameter, "$(name)", s]
                      - [grel:valueParameter2, "$(friendName)", o]
  myOtherMapping:
    sources:
      - ["data2.csv~csv"]
    s: http://example.com#heroes_$(ID)
    po:
      - [a, ex:Hero]
      - [ex:label, $(name)]
```

### Steps
Trying to execute the parsed RML makes the RMLMapper error `Cannot find friendID in data.csv`

### Environment
Matey

**Comment by pheyvaer** [comment]
What exactly is the issue? Could you provide the expected RML?

**Comment by bjdmeest** [comment]
I guess if it means that rr:parentTriplesMap is inherited in nested functions, then yes, it's a bug in the RMLMapper :). In any case, I guess the mapper shouldn't try its own logicalsource if it cannot find the parenttriplesmap's source.. Made an RMLMapper-java issue! https://github.com/RMLio/rmlmapper-java/issues/53

**Comment by bjdmeest** [comment]
For completeness: this _very specific use case_ is in fact a non issue. Conforming to R2RML, if you specify multiple conditions on one join condition, they are de facto assumed to be conjunctive (i.e., an AND operator), see https://www.w3.org/TR/r2rml/#dfn-joint-sql-query : you can have multiple join conditions.

So this very specific use case could be rephrased into the following, excluding the need for `boolean_and`, and thus you have no issue. **but beware** because this would not work for other kinds of compositions (eg `boolean_or`):

```yaml
prefixes:
  ex: http://example.com#
  grel: http://users.ugent.be/~bjdmeest/function/grel.ttl#
  idlab-fn: "http://example.com/idlab/function/"

mappings:
  myMapping:
    sources:
      - ["data.csv~csv"]
    s: ex:$(ID)
    po:
      - [a, ex:Person]
      - [ex:label, $(name)]
      - p: ex:isFriendsWith
        o:
          - mapping: myOtherMapping
            condition:
              - function: idlab-fn:equal
                parameters:
                  - [grel:valueParameter, "$(otherID)", s]
                  - [grel:valueParameter2, "$(friendID)", o]
              - function: idlab-fn:equal
                parameters:
                  - [grel:valueParameter, "$(name)", s]
                  - [grel:valueParameter2, "$(friendName)", o]
  myOtherMapping:
    sources:
      - ["data2.csv~csv"]
    s: http://example.com#heroes_$(ID)
    po:
      - [a, ex:Hero]
      - [ex:label, $(name)]
```
