### ISSUE TITLE
Conditional predicate-object with datatype

### ISSUE THREAD

**Issue by SvenLieber** [RMLio/yarrrml-parser#69]
### Description
I have a conditional mapping which works well. However, when splitting the *object*-part into *value* and *datatype*, the datatype will not be in the output.

### Steps

The following mapping does not produce a datatype for `end_date` in the output, but I assume it should according to example 55 from the [YARRRML spec](https://rml.io/yarrrml/spec/#datatypes).

**Input**
```
id,start_date,end_date
1,2020-04-21,
2,2019-04-21,2019-04-24
```

**YARRRML mapping**
```
prefixes: 
  ex: "https://example.org/ns/test#"
  idlab-fn: "http://example.com/idlab/function/"
  grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"
  xsd: "http://www.w3.org/2001/XMLSchema#"
  prov: "http://www.w3.org/ns/prov#"

mappings:

  events:
    sources:
      - ['minimal-examples/minimal-example-empty-date-type.csv~csv']
    s: ex:event_$(id)
    po: 
      - [a, ex:Event]
      - [prov:startedAtTime, $(start_date), xsd:dateTime]
      - p: prov:endedAtTime
        o:
          - value: $(end_date)
            datatype: xsd:dateTime
        condition:
          function: idlab-fn:notEqual
          parameters:
            - [grel:valueParameter, $(end_date)]
            - [grel:valueParameter2, ""] 

```

**Output**
```
<https://example.org/ns/runi-data#event_1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/runi/ns/core#Event>.
<https://example.org/ns/runi-data#event_1> <http://www.w3.org/ns/prov#startedAtTime> "2020-04-21"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://example.org/ns/runi-data#event_2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/runi/ns/core#Event>.
<https://example.org/ns/runi-data#event_2> <http://www.w3.org/ns/prov#startedAtTime> "2019-04-21"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://example.org/ns/runi-data#event_2> <http://www.w3.org/ns/prov#endedAtTime> "2019-04-24".

```

### Environment

* Ubuntu 16.04
* yarrrml-parser 1.0.2
* rmlmapper-java 4.7.0-r159
* openJDK 12.0.2
