### ISSUE TITLE
Datatype on conditional mapping is not set

### ISSUE THREAD

**Issue by julianrojas87** [RMLio/yarrrml-parser#76]
### Description
Defining a specific datatype in a conditional mapping does not add the `rr:datatype xsd:boolean` triple to the corresponding `rr:ObjectMap`.
### Steps
Example data
```csv
ID,Direction
1,N
2,O
```
Mappings:
```yaml

s: ex:entity$(ID)
p: ex:param
    o: 
        value: "false"
        datatype: xsd:boolean
    condition:
        function: idlab-fn:equal
            parameters:
                - [grel:valueParameter, $(Direction)]
                - [grel:valueParameter2, "N"]
```
Resulting RML:
```turtle
:om_37 a rr:ObjectMap;
    rr:constant "false";
    rr:termType rr:Literal.
```

### Environment
OS: Ubuntu 20.04 LTS
Node.js: v13.7.0
YARRRML: v1.1.0

**Comment by pheyvaer** [comment]
@julianrojas87 The YARRRML rules are invalid. Are these the ones you used?

**Comment by pheyvaer** [comment]
The description of the issue looks like it's the same as [this test](https://github.com/RMLio/yarrrml-parser/blob/development/test/condition-on-po-datatype/mapping.yarrrml), which passes.

**Comment by julianrojas87** [comment]
Sorry for the delayed answer. 
 - First: yes, the above mappings are wrong but are not the actual ones I was using. The correct ones are:
```yaml
prefixes:
  idlab-fn: "http://example.com/idlab/function/"
  grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"
  xsd: "http://www.w3.org/2001/XMLSchema#"
  ex: "http://example.org#"
mappings:
  test:
    sources:
      - ["test.csv~csv"]
    s: ex:entity$(ID)
    po:
      - p: ex:param
        o: 
          - value: "false"
            datatype: xsd:boolean
        condition:
          function: idlab-fn:equal
          parameters:
            - [grel:valueParameter, $(Direction)]
            - [grel:valueParameter2, "N"]
      - p: ex:param
        o: 
          - value: "true"
            datatype: xsd:boolean
        condition:
          function: idlab-fn:equal
          parameters:
            - [grel:valueParameter, $(Direction)]
            - [grel:valueParameter2, "O"]

```
Second: After comparing my resulting RML to the one from passing test you linked above, I noticed that the difference comes on the definitions of the `fnml:FunctionTermMap`s which are missing the `rr:datatype xsd:boolean;`. E.g.:
```ttl
:om_0 a fnml:FunctionTermMap;
    rr:termType rr:Literal;
    fnml:functionValue :fn_0.
```
However, I was initially testing on `v1.1.0` but as you pointed, it is already corrected on `v1.1.1`. So I think this issue can be closed.
